tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      cd frontend-react-js
      npm install
      cd ..
      clear
  - name: postgres
    init: |
      cd /workspace
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      cd $THEIA_WORKSPACE_ROOT
      pyenv install 3.10.9
      pyenv global 3.10.9
      clear
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2 
    - ms-azuretools.vscode-docker
    - ms-python.python

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
    name: Frontend 
  - port: 4567
    name: Backend
    visibility: public
    onOpen: open-browser
  - port: 2000
    name: x-ray-daemon
    visibility: public
